### ISSUE TITLE
Readme does not uses PEP-621

### ISSUE THREAD

**Issue by gaborbernat** [optiver/vulcan-py#15]
See https://github.com/optiver/vulcan-py#dependencies

**Comment by Thirdegree** [comment]
Ah, this is intentional. Vulcan does not allow the pep621 `dependencies` and `extra-dependencies` keys, because it uses a lockfile and I wanted to disabiguate what those keys mean. So `vulcan.tool.dependencies` is the dependencies that are used to generate the lockfile, and keeping that a seperate tool-speific key makes that explicit
